itemDict:
    'sntemp_inputs_outputs_drb.zip': '5f6a289982ce38aaa2449135'
    'temperature_observations_drb.zip': '5f6a287382ce38aaa2449131'
    'flow_observations_drb.zip': '5f6a287382ce38aaa2449131'

subsetDict: 
    Christiana: "ChristianaReaches.csv"


outDir: "dataDir"

tarFiles: True
