name: river_dl_data_prep
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - numpy
    - pandas
    - xarray
    - dask
    - zarr
    - pip
    - snakemake
    - pip:
          - sciencebasepy
